services:
    mongo:
        image: mongo
        ports:
            - '27017:27017'
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: robin
            POSTGRES_PASSWORD: burri
        ports:
            - '5432:5432'
